### PR TITLE
Delete photos only from DB when deleting from filesystem was successf…

### PR DESCRIPTION
**Pull request by westnordost**
…ul, log error

### CODE REVIEW

**Comment by exploide** [comment]
Thanks for investigating the problem that occurred on production! May I ask what the motivation for these changes was, since the actual problem was about absolute paths?

I'm a bit unsure about the changes.

- this hinders point 7 from #1 since deleting files manually would lead to inconsistent DB state
- deleting all photos individually is probably less performant (but might be acceptable for our scenario)
- in `deletePhoto`, the part `$photo['file_id']==NULL?` should be `note_id` not `file_id` I guess?! It's building the wrong path currently. (and it must be ensured the db helper functions return also the `photo_id`)
- why the `echo error_get_last()["message"]` when `unlink` emmits a warning anyway when something goes wrong?

**Comment by westnordost** [comment]
1. Inconsistent, but at least the script will log this every time. Deleting the photos from db when they are still on the disk leads itself to an inconsistent state.
2. it is in the  milliseconds at most
3. Uhm right, yes.
4. Because it didn't for me. I don't know where the warning was logged to, I didn't see it anywhere

Am 8. Oktober 2018 18:02:49 MESZ schrieb Jannik Vieten <notifications@github.com>:
>Thanks for investigating the problem that occurred on production! May I
>ask what the motivation for these changes was, since the actual problem
>was about absolute paths?
>
>I'm a bit unsure about the changes.
>
>- this hinders point 7 from #1 since deleting files manually would lead
>to inconsistent DB state
>- deleting all photos individually is probably less performant (but
>might be acceptable for our scenario)
>- in `deletePhoto`, the part `$photo['file_id']==NULL?` should be
>`note_id` not `file_id` I guess?! It's building the wrong path
>currently. (and it must be ensured the db helper functions return also
>the `photo_id`)
>- why the `echo error_get_last()["message"]` when `unlink` emmits a
>warning anyway when something goes wrong?

**Comment by exploide** [comment]
Ok, I think avoiding inconsistency by default and alerting whenever this is detected is reasonable.

I'll merge this soon, then do a bit cleanup and fix few (other) things I have in mind.

Afterwards I ping you once it is done, so you can deploy updated master.

**Comment by westnordost** [comment]
Great, thanks!

**Comment by exploide** [comment]
@westnordost I'm done so far. You can deploy.

Concerning the point why you got no warning by PHP: I think now this is because the error_reporting is configured less verbose for your webspace than on my dev machine. I thought about fiddling with this in PHP but then decided to leave it as is, let it print the warning you introduced and hope that you will also see errors if the database will be down for some reason (I don't know in this scenario for you webspace..).

So, hopefully we are done now ;)

**Comment by westnordost** [comment]
Deployed, thanks :-)

99 photos currently active, by the way, 144 MB. Per day, on average a dozen new photos are uploaded.

**Pull request merged**
